# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pieces._vendor.pieces_os_client.models.asset_filter_phrase import AssetFilterPhrase
from pieces._vendor.pieces_os_client.models.asset_filter_timestamp import AssetFilterTimestamp
from pieces._vendor.pieces_os_client.models.classification_specific_enum import ClassificationSpecificEnum
from pieces._vendor.pieces_os_client.models.embedded_model_schema import EmbeddedModelSchema
from typing import Optional, Set
from typing_extensions import Self

class AssetFilter(BaseModel):
    """
    ** in the future, consider adding an optional bool's called nextAnd, nextOr which will say that the next filter will be  AND behavor or OR behavior.  \"operations\": here is is an optional property to allow or behavior,(we will only allow 1 level deep of or's), if or is not passed in then it is just simply ignored. If or is passed in then we will be or'd together with the top level filter and considered extras. default behavior for operations is and, however yoour can specifiy OR operations as well.
    """ # noqa: E501
    classification: Optional[ClassificationSpecificEnum] = None
    created: Optional[AssetFilterTimestamp] = None
    operations: Optional[AssetFilters] = None
    persons: Optional[List[StrictStr]] = None
    phrase: Optional[AssetFilterPhrase] = None
    var_schema: Optional[EmbeddedModelSchema] = Field(default=None, alias="schema")
    tags: Optional[List[StrictStr]] = None
    updated: Optional[AssetFilterTimestamp] = None
    websites: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["classification", "created", "operations", "persons", "phrase", "schema", "tags", "updated", "websites"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssetFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created
        if self.created:
            _dict['created'] = self.created.to_dict()
        # override the default output from pydantic by calling `to_dict()` of operations
        if self.operations:
            _dict['operations'] = self.operations.to_dict()
        # override the default output from pydantic by calling `to_dict()` of phrase
        if self.phrase:
            _dict['phrase'] = self.phrase.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_schema
        if self.var_schema:
            _dict['schema'] = self.var_schema.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated
        if self.updated:
            _dict['updated'] = self.updated.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssetFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "classification": obj.get("classification"),
            "created": AssetFilterTimestamp.from_dict(obj["created"]) if obj.get("created") is not None else None,
            "operations": AssetFilters.from_dict(obj["operations"]) if obj.get("operations") is not None else None,
            "persons": obj.get("persons"),
            "phrase": AssetFilterPhrase.from_dict(obj["phrase"]) if obj.get("phrase") is not None else None,
            "schema": EmbeddedModelSchema.from_dict(obj["schema"]) if obj.get("schema") is not None else None,
            "tags": obj.get("tags"),
            "updated": AssetFilterTimestamp.from_dict(obj["updated"]) if obj.get("updated") is not None else None,
            "websites": obj.get("websites")
        })
        return _obj

from pieces._vendor.pieces_os_client.models.asset_filters import AssetFilters
# TODO: Rewrite to not use raise_errors
AssetFilter.model_rebuild(raise_errors=False)

