# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pieces._vendor.pieces_os_client.models.embedded_model_schema import EmbeddedModelSchema
from pieces._vendor.pieces_os_client.models.entity_type_enum import EntityTypeEnum
from pieces._vendor.pieces_os_client.models.flattened_subscriptions import FlattenedSubscriptions
from pieces._vendor.pieces_os_client.models.flattened_users import FlattenedUsers
from pieces._vendor.pieces_os_client.models.grouped_timestamp import GroupedTimestamp
from pieces._vendor.pieces_os_client.models.instance_configuration import InstanceConfiguration
from pieces._vendor.pieces_os_client.models.score import Score
from typing import Optional, Set
from typing_extensions import Self

class Entity(BaseModel):
    """
    An Entity represents either an Organization or a Team.   NOTE: org/team identifier will be present if it is a org vs a team.
    """ # noqa: E501
    configuration: InstanceConfiguration
    created: GroupedTimestamp
    deleted: Optional[GroupedTimestamp] = None
    domains: Optional[List[StrictStr]] = Field(default=None, description="List of associated domains for this entity")
    id: StrictStr = Field(description="This will be a uuid")
    name: StrictStr = Field(description="Display name of the entity")
    org_identifier: Optional[StrictStr] = Field(default=None, description="this is the id that represents the org in the user-team service")
    var_schema: Optional[EmbeddedModelSchema] = Field(default=None, alias="schema")
    score: Optional[Score] = None
    subscriptions: Optional[FlattenedSubscriptions] = None
    team_identifier: Optional[StrictStr] = Field(default=None, description="this is the id that represents the org in the user-team service")
    type: EntityTypeEnum
    updated: GroupedTimestamp
    users: Optional[FlattenedUsers] = None
    __properties: ClassVar[List[str]] = ["configuration", "created", "deleted", "domains", "id", "name", "org_identifier", "schema", "score", "subscriptions", "team_identifier", "type", "updated", "users"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Entity from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of configuration
        if self.configuration:
            _dict['configuration'] = self.configuration.to_dict()
        # override the default output from pydantic by calling `to_dict()` of created
        if self.created:
            _dict['created'] = self.created.to_dict()
        # override the default output from pydantic by calling `to_dict()` of deleted
        if self.deleted:
            _dict['deleted'] = self.deleted.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_schema
        if self.var_schema:
            _dict['schema'] = self.var_schema.to_dict()
        # override the default output from pydantic by calling `to_dict()` of score
        if self.score:
            _dict['score'] = self.score.to_dict()
        # override the default output from pydantic by calling `to_dict()` of subscriptions
        if self.subscriptions:
            _dict['subscriptions'] = self.subscriptions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of updated
        if self.updated:
            _dict['updated'] = self.updated.to_dict()
        # override the default output from pydantic by calling `to_dict()` of users
        if self.users:
            _dict['users'] = self.users.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Entity from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configuration": InstanceConfiguration.from_dict(obj["configuration"]) if obj.get("configuration") is not None else None,
            "created": GroupedTimestamp.from_dict(obj["created"]) if obj.get("created") is not None else None,
            "deleted": GroupedTimestamp.from_dict(obj["deleted"]) if obj.get("deleted") is not None else None,
            "domains": obj.get("domains"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "org_identifier": obj.get("org_identifier"),
            "schema": EmbeddedModelSchema.from_dict(obj["schema"]) if obj.get("schema") is not None else None,
            "score": Score.from_dict(obj["score"]) if obj.get("score") is not None else None,
            "subscriptions": FlattenedSubscriptions.from_dict(obj["subscriptions"]) if obj.get("subscriptions") is not None else None,
            "team_identifier": obj.get("team_identifier"),
            "type": obj.get("type"),
            "updated": GroupedTimestamp.from_dict(obj["updated"]) if obj.get("updated") is not None else None,
            "users": FlattenedUsers.from_dict(obj["users"]) if obj.get("users") is not None else None
        })
        return _obj


