# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class FoundryDeploymentStatusEnum(str, Enum):
    """
    Enum used for the status of Foundry
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    INITIALIZED = 'INITIALIZED'
    IN_MINUS_PROGRESS = 'IN-PROGRESS'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    CANCELED = 'CANCELED'
    RESET = 'RESET'

    @classmethod
    def from_json(cls, json_str: str) -> FoundryDeploymentStatusEnum:
        """Create an instance of FoundryDeploymentStatusEnum from a JSON string"""
        return FoundryDeploymentStatusEnum(json.loads(json_str))


