# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class HasFeatureAccessEnum(str, Enum):
    """
    Enum representing different feature access types for instance configuration.
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    CONNECT_TO_CLOUD = 'CONNECT_TO_CLOUD'
    UPDATE_ALLOCATION_CLOUD = 'UPDATE_ALLOCATION_CLOUD'
    RECONNECT_TO_CLOUD = 'RECONNECT_TO_CLOUD'
    SHARE_SNIPPET = 'SHARE_SNIPPET'
    CLOUD_BACKUP_CREATION = 'CLOUD_BACKUP_CREATION'
    LIST_CLOUD_BACKUPS = 'LIST_CLOUD_BACKUPS'
    LIST_SPECIFIC_CLOUD_BACKUP = 'LIST_SPECIFIC_CLOUD_BACKUP'
    RESTORE_CLOUD_BACKUP = 'RESTORE_CLOUD_BACKUP'
    DELETE_CLOUD_BACKUP = 'DELETE_CLOUD_BACKUP'
    IP_LOOKUP = 'IP_LOOKUP'
    SENTRY = 'SENTRY'
    BIG_QUERY = 'BIG_QUERY'
    SEGMENT = 'SEGMENT'
    CUSTOM_ANALYTICS = 'CUSTOM_ANALYTICS'
    SEND_INTERNAL_SUMMARY_REPORTS_TO_USER_TEAM_SERVICE = 'SEND_INTERNAL_SUMMARY_REPORTS_TO_USER_TEAM_SERVICE'
    ALLOWED_CLOUD_MODELS = 'ALLOWED_CLOUD_MODELS'
    DENIED_WORKSTREAM_PATTERN_ENGINE_SOURCES = 'DENIED_WORKSTREAM_PATTERN_ENGINE_SOURCES'
    DENIED_WORKSTREAM_PATTERN_ENGINE_WEBSITES = 'DENIED_WORKSTREAM_PATTERN_ENGINE_WEBSITES'
    EXTERNAL_PROVIDER_PROCESSING = 'EXTERNAL_PROVIDER_PROCESSING'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HasFeatureAccessEnum from a JSON string"""
        return cls(json.loads(json_str))




    @classmethod
    def _missing_(cls, value):
        # Called when `value` doesn't match any member
        return cls.UNKNOWN

