# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from pieces._vendor.pieces_os_client.models.conversation import Conversation
from pieces._vendor.pieces_os_client.models.embedded_model_schema import EmbeddedModelSchema
from pieces._vendor.pieces_os_client.models.searched_annotations import SearchedAnnotations
from pieces._vendor.pieces_os_client.models.searched_conversation_messages import SearchedConversationMessages
from typing import Optional, Set
from typing_extensions import Self

class SearchedConversation(BaseModel):
    """
    This is used for the Conversations searching endpoint.  conversation here is only provided if transferables are set to true.  temporal: if this is provided this means that their material matched the input via a timestamp.  TODO will want to consider returning related materials to this material potentially both associated/ and not associated materials ie suggestion: WorkstreamSuggestions
    """ # noqa: E501
    annotations: Optional[SearchedAnnotations] = None
    conversation: Optional[Conversation] = None
    exact: StrictBool
    identifier: StrictStr = Field(description="This is the uuid of the conversation.")
    messages: Optional[SearchedConversationMessages] = None
    var_schema: Optional[EmbeddedModelSchema] = Field(default=None, alias="schema")
    similarity: Union[StrictFloat, StrictInt]
    temporal: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["annotations", "conversation", "exact", "identifier", "messages", "schema", "similarity", "temporal"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchedConversation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of annotations
        if self.annotations:
            _dict['annotations'] = self.annotations.to_dict()
        # override the default output from pydantic by calling `to_dict()` of conversation
        if self.conversation:
            _dict['conversation'] = self.conversation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of messages
        if self.messages:
            _dict['messages'] = self.messages.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_schema
        if self.var_schema:
            _dict['schema'] = self.var_schema.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchedConversation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "annotations": SearchedAnnotations.from_dict(obj["annotations"]) if obj.get("annotations") is not None else None,
            "conversation": Conversation.from_dict(obj["conversation"]) if obj.get("conversation") is not None else None,
            "exact": obj.get("exact"),
            "identifier": obj.get("identifier"),
            "messages": SearchedConversationMessages.from_dict(obj["messages"]) if obj.get("messages") is not None else None,
            "schema": EmbeddedModelSchema.from_dict(obj["schema"]) if obj.get("schema") is not None else None,
            "similarity": obj.get("similarity"),
            "temporal": obj.get("temporal")
        })
        return _obj


