# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pieces._vendor.pieces_os_client.models.embedded_model_schema import EmbeddedModelSchema
from pieces._vendor.pieces_os_client.models.grouped_timestamp import GroupedTimestamp
from pieces._vendor.pieces_os_client.models.subscription_term_enum import SubscriptionTermEnum
from typing import Optional, Set
from typing_extensions import Self

class UserTeamServiceOrganizationSubscription(BaseModel):
    """
    This is the descope user subscription
    """ # noqa: E501
    active: StrictBool
    canceled_at: Optional[GroupedTimestamp] = None
    created_at: GroupedTimestamp
    name: StrictStr
    nextbilled_at: Optional[GroupedTimestamp] = None
    paused_at: Optional[GroupedTimestamp] = None
    price_id: StrictStr
    product_id: StrictStr
    quantity: StrictInt
    var_schema: Optional[EmbeddedModelSchema] = Field(default=None, alias="schema")
    subscription_id: StrictStr
    term: SubscriptionTermEnum
    __properties: ClassVar[List[str]] = ["active", "canceled_at", "created_at", "name", "nextbilled_at", "paused_at", "price_id", "product_id", "quantity", "schema", "subscription_id", "term"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserTeamServiceOrganizationSubscription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of canceled_at
        if self.canceled_at:
            _dict['canceled_at'] = self.canceled_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of created_at
        if self.created_at:
            _dict['created_at'] = self.created_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of nextbilled_at
        if self.nextbilled_at:
            _dict['nextbilled_at'] = self.nextbilled_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of paused_at
        if self.paused_at:
            _dict['paused_at'] = self.paused_at.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_schema
        if self.var_schema:
            _dict['schema'] = self.var_schema.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserTeamServiceOrganizationSubscription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "canceled_at": GroupedTimestamp.from_dict(obj["canceled_at"]) if obj.get("canceled_at") is not None else None,
            "created_at": GroupedTimestamp.from_dict(obj["created_at"]) if obj.get("created_at") is not None else None,
            "name": obj.get("name"),
            "nextbilled_at": GroupedTimestamp.from_dict(obj["nextbilled_at"]) if obj.get("nextbilled_at") is not None else None,
            "paused_at": GroupedTimestamp.from_dict(obj["paused_at"]) if obj.get("paused_at") is not None else None,
            "price_id": obj.get("price_id"),
            "product_id": obj.get("product_id"),
            "quantity": obj.get("quantity"),
            "schema": EmbeddedModelSchema.from_dict(obj["schema"]) if obj.get("schema") is not None else None,
            "subscription_id": obj.get("subscription_id"),
            "term": obj.get("term")
        })
        return _obj


