# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pieces._vendor.pieces_os_client.models.embedded_model_schema import EmbeddedModelSchema
from pieces._vendor.pieces_os_client.models.grouped_timestamp import GroupedTimestamp
from pieces._vendor.pieces_os_client.models.window_dimensions import WindowDimensions
from typing import Optional, Set
from typing_extensions import Self

class WorkstreamPatternEngineVisionCalibration(BaseModel):
    """
    This model is used for the dimensions of the copilot/feed/xyz window.  if dimensions/captured are null this means we do not have the dimensions for this given window.  TODO: consider adding 5 markers here for the qr codes(ie location of these as wel) NOTE: will want to add type of calibration for this specific dimension(ie copilot/feed/xyz)
    """ # noqa: E501
    captured: Optional[GroupedTimestamp] = None
    dimensions: Optional[WindowDimensions] = None
    foreground: StrictStr = Field(description="This is the name of the window(foreground window).(this will always be present)")
    var_schema: Optional[EmbeddedModelSchema] = Field(default=None, alias="schema")
    __properties: ClassVar[List[str]] = ["captured", "dimensions", "foreground", "schema"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkstreamPatternEngineVisionCalibration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of captured
        if self.captured:
            _dict['captured'] = self.captured.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dimensions
        if self.dimensions:
            _dict['dimensions'] = self.dimensions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of var_schema
        if self.var_schema:
            _dict['schema'] = self.var_schema.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkstreamPatternEngineVisionCalibration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "captured": GroupedTimestamp.from_dict(obj["captured"]) if obj.get("captured") is not None else None,
            "dimensions": WindowDimensions.from_dict(obj["dimensions"]) if obj.get("dimensions") is not None else None,
            "foreground": obj.get("foreground"),
            "schema": EmbeddedModelSchema.from_dict(obj["schema"]) if obj.get("schema") is not None else None
        })
        return _obj


