# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.interacted_assets import InteractedAssets  # noqa: E501

class TestInteractedAssets(unittest.TestCase):
    """InteractedAssets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InteractedAssets:
        """Test InteractedAssets
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InteractedAssets`
        """
        model = InteractedAssets()  # noqa: E501
        if include_optional:
            return InteractedAssets(
                var_schema = openapi_client.models.embedded_model_schema.EmbeddedModelSchema(
                    migration = 56, 
                    semantic = 'MAJOR_0_MINOR_0_PATCH_1', ),
                iterable = [
                    openapi_client.models.interacted_asset.InteractedAsset(
                        asset = '6a2f41a3-c54c-fce8-32d2-0324e1c32e22', 
                        interactions = openapi_client.models.interacted_asset_interactions.InteractedAsset_interactions(
                            viewed = 'PY-M-DTh:m:s', 
                            touched = True, 
                            scrolled = True, ), )
                    ]
            )
        else:
            return InteractedAssets(
                iterable = [
                    openapi_client.models.interacted_asset.InteractedAsset(
                        asset = '6a2f41a3-c54c-fce8-32d2-0324e1c32e22', 
                        interactions = openapi_client.models.interacted_asset_interactions.InteractedAsset_interactions(
                            viewed = 'PY-M-DTh:m:s', 
                            touched = True, 
                            scrolled = True, ), )
                    ],
        )
        """

    def testInteractedAssets(self):
        """Test InteractedAssets"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
