# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.seeded_tracked_adoption_event import SeededTrackedAdoptionEvent  # noqa: E501

class TestSeededTrackedAdoptionEvent(unittest.TestCase):
    """SeededTrackedAdoptionEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SeededTrackedAdoptionEvent:
        """Test SeededTrackedAdoptionEvent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SeededTrackedAdoptionEvent`
        """
        model = SeededTrackedAdoptionEvent()  # noqa: E501
        if include_optional:
            return SeededTrackedAdoptionEvent(
                var_schema = openapi_client.models.embedded_model_schema.EmbeddedModelSchema(
                    migration = 56, 
                    semantic = 'MAJOR_0_MINOR_0_PATCH_1', ),
                identifier_description_pair = openapi_client.models.analytics_tracked_adoption_event_identifier_description_pairs.AnalyticsTrackedAdoptionEventIdentifierDescriptionPairs(
                    schema = openapi_client.models.embedded_model_schema.EmbeddedModelSchema(
                        migration = 56, 
                        semantic = 'MAJOR_0_MINOR_0_PATCH_1', ), 
                    adoption_install = 'the_user_has_installed_a_pieces_application', 
                    adoption_uninstall = 'the_user_has_uninstalled_a_pieces_application', )
            )
        else:
            return SeededTrackedAdoptionEvent(
        )
        """

    def testSeededTrackedAdoptionEvent(self):
        """Test SeededTrackedAdoptionEvent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
