# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.node_type_enum import NodeTypeEnum  # noqa: E501

class TestNodeTypeEnum(unittest.TestCase):
    """NodeTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeTypeEnum(self):
        """Test NodeTypeEnum"""
        # inst = NodeTypeEnum()

if __name__ == '__main__':
    unittest.main()
