# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.discovery_api import DiscoveryApi  # noqa: E501


class TestDiscoveryApi(unittest.TestCase):
    """DiscoveryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DiscoveryApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_discovery_discover_assets(self) -> None:
        """Test case for discovery_discover_assets

        /discovery/discover/assets [POST]  # noqa: E501
        """
        pass

    def test_discovery_discover_assets_html(self) -> None:
        """Test case for discovery_discover_assets_html

        /discovery/discover/assets/html[POST]  # noqa: E501
        """
        pass

    def test_discovery_discover_sensitives(self) -> None:
        """Test case for discovery_discover_sensitives

        /discovery/discover/sensitives [POST]  # noqa: E501
        """
        pass

    def test_discovery_discover_tags_related(self) -> None:
        """Test case for discovery_discover_tags_related

        /discovery/discover/tags/related [POST]  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
