# coding: utf-8

"""
    Pieces Isomorphic OpenAPI

    Endpoints for Assets, Formats, Users, Asset, Format, User.

    The version of the OpenAPI document: 1.0
    Contact: tsavo@pieces.app
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.person_api import PersonApi  # noqa: E501


class TestPersonApi(unittest.TestCase):
    """PersonApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PersonApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_person_scores_increment(self) -> None:
        """Test case for person_scores_increment

        '/person/{person}/scores/increment' [POST]  # noqa: E501
        """
        pass

    def test_person_snapshot(self) -> None:
        """Test case for person_snapshot

        /person/{person} [GET]  # noqa: E501
        """
        pass

    def test_update_person(self) -> None:
        """Test case for update_person

        /person/update [POST]  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
