name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      deploy: true
    secrets:
      access_token: ${{ secrets.GITHUB_TOKEN }}

